### ISSUE TITLE
Pytorch equivalent for s2i-tensorflow images

### ISSUE THREAD

**Issue by anishasthana** [thoth-station/s2i-pytorch-notebook#1]
**Is your feature request related to a problem? Please describe.**
There are a lot of Jupyterhub users who like using Pytorch as their ml library of choice.

**Describe the solution you'd like**
I think having a repo similar to this but for Pytorch would be great for the ODH. We can include it as some of the additional images on there.

**Describe alternatives you've considered**
Don't think there really is one

**Additional context**
I'm happy to do the initial work on this, just need to know where I'd be working :-)

**Comment by harshad16** [comment]
The next step would be to figure out, what all packages would be useful to install along with PyTorch.

**Comment by harshad16** [comment]
The s2i-pytorch-notebook is now available as a container image https://quay.io/repository/thoth-station/s2i-pytorch-notebook .
Seems to satisfy the issue. 
closing it .
