### ISSUE TITLE
Tensorboard is not available

### ISSUE THREAD

**Issue by chauhankaranraj** [thoth-station/s2i-pytorch-notebook#4]
**Describe the bug**
Tensorboard is not pre-installed in the image. So when a user tries to use tensorboard utils, it throws an error.

**To Reproduce**
1. Go to https://jupyterhub.datahub.redhat.com
2. Click on `s2i-pytorch-notebook:latest` and click `Spawn`
3. Open a notebook and and run the following line:
```
from torch.utils.tensorboard import SummaryWriter
```

**Expected behavior**
Tensorboard utils should get imported without error

**Screenshots**
![Screenshot from 2020-11-02 12-30-57](https://user-images.githubusercontent.com/15005500/97899506-64ea8600-1d07-11eb-8ae0-b8bcb5198b1d.png)

**Additional context**
I think just adding `tensorboard` to Pipfile should fix it.

Also, it looks like `jupyter-tensorboard` plugin has compatibility issues with tensorboard > 2.0 (see lspvic/jupyter_tensorboard#55, lspvic/jupyter_tensorboard#68), so maybe `tensorboard = "<2.0"` should be added to Pipfile

**Comment by harshad16** [comment]
Thanks for checking out the image and for the valuable feedback. :+1:

**Comment by goern** [comment]
@accorvin could you validate that the new image is available in internal Data Hub? it should be quay.io/thoth-station/s2i-pytorch-notebook:v0.0.2

@chauhankaranraj  could you please recheck the new image?

**Comment by anishasthana** [comment]
He's tested the 0.0.2 image, we are now working on a CUDA image. Closing this issue
